config/routes.rb
Rails.application.routes.draw do
  get 'areas/edit'

  get 'areas/update'

  get 'categories/edit'

  root 'pages#home'
  resources :users, :posts, :categories, :areas
  resources :tenders do
    resources :answers
    member do
      get :update_status
    end
  end

  resources :admin, only: :index do

  end

  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  get 'home' => 'pages#home'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'admin' => 'pages#admin_tenders'
  get 'admin_tenders' => 'pages#admin_tenders'
  get 'admin_categories' => 'pages#admin_categories'
  get 'admin_areas' => 'pages#admin_areas'

=begin
  get 'posts' => 'posts#index'
  get 'posts/new' => 'posts#new'
  get '/posts/:id' => 'posts#show', as: :post
  get '/posts/:id/edit' => 'posts#edit', as: :edit_post
  patch '/posts/:id' => 'posts#update'

  get 'tenders' => 'tenders#index'
  get 'tenders/new' => 'tenders#new'
  get 'tenders/:id' => 'tenders#show', as: :tender
  get '/tenders/:id/edit' => 'tenders#edit', as: :edit_tender
  patch '/tenders/:id' => 'tenders#update'
=end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :tender
  belongs_to :user
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :tenders
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tenders
end

app/models/concerns/Filterable.rb
module Filterable
  extend ActiveSupport::Concern
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tag_to_tenders
  has_many :tenders, :through=> :tag_to_tenders
end

app/models/tag_to_tender.rb
class TagToTender < ActiveRecord::Base
  belongs_to :tender
  belongs_to :tag
end

app/models/tender.rb
class Tender < ActiveRecord::Base
  has_many :tag_to_tenders
  has_many :tags, :through => :tag_to_tenders
  belongs_to :area
  belongs_to :category
  belongs_to :user
  has_many :answers

  scope :status, -> (status) { where status: status }
  scope :area, -> (area) { where area: area }
  scope :category, -> (category) { where category: category }
  scope :tenders_like, -> (title) { where("title like ?", "#{title}%")}

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :tenders
  has_many :answers

  has_secure_password

  def user?
    self.role == 'user'
  end

  def admin?
    self.role == 'admin'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/' unless current_user.user?
  end

  def require_admin
    redirect_to '/' unless current_user.admin?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :current_user, :require_admin, only: [:admin_areas, :admin_tenders]

  def home
  end

  def admin_tenders
    @tenders = Tender.where(nil)
    filtering_params(params).each do |key, value|
      @tenders = @tenders.public_send(key, value) if value.present?
    end
  end

  def admin_categories
    @categories = Category.all
    end

  def admin_areas
    @areas = Area.all
  end

  private

  def filtering_params(params)
    params.slice(:status, :area, :category, :tenders_like)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :require_user, only: [:index, :show]

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to 'news'
    else
      redirect_to 'posts/new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @author = @post.user
  end

  def index
    @posts = Post.order(created_at: :desc)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to 'posts'
  end

  private

    def post_params
      params.require(:post).permit(:title_en, :title_ru, :text_en, :text_ru, :preview)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to 'login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/tenders_controller.rb
class TendersController < ApplicationController
  def new
    @tender = Tender.new
    @categories = Category.all
    @areas = Area.all
  end

  def show
    @tender = Tender.find(params[:id])
  end

  def destroy
    @tender = Tender.destroy(params[:id])
    redirect_to 'admin_tenders'
  end

  def create
    @tender = Tender.create(tender_params.except(:category, :area)) do |t|
      t.user_id = current_user.id
      t.category_id = tender_params[:category]
      t.area_id = tender_params[:area]
      t.status = 'in_progress'
    end
    if @tender.save
      redirect_to 'tenders'
    else
      redirect_to 'posts/new'
    end
  end

  def update_status
    @tender = Tender.find(params[:id])
    @tender.update(status: 'modered')
  end

  def index
    @posts = Post.order(created_at: :desc).first(4)
    @categories = Category.all
    @tenders = Tender.where(nil)
    filtering_params(params).each do |key, value|
      @tenders = @tenders.public_send(key, value) if value.present?
    end
  end

  private

  def filtering_params(params)
    params.slice(:status, :area, :category, :tenders_like)
  end

  def tender_params
    params.require(:tender).permit(:title, :content, :address, :category, :area, :amount, :currency, :deadline)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :number, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tender_helper.rb
module TenderHelper
end

app/helpers/tenders_helper.rb
module TendersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="top-menu">
    <%= link_to image_tag('logo_on_transparent_372x75.png'), '../' %>
    <ul class="lang">
      <!--<li><a href="#">RU</a></li>-->
      <!--<li><a href="#">UA</a></li>-->
      <!--<li><a href="#">EN</a></li>-->
    </ul>
  </div>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!--<a class="navbar-brand" href="#">Tender</a>-->
      </div>

      <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <% if current_user %>
        <ul class="nav navbar-nav">
          <li class="active"><a href="../tenders">Все тендеры</a></li>
          <!--<li><a href="#">Мои тендеры</a></li>-->
          <!--<li><a href="#">Мои предложения</a></li>-->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user && current_user.admin? %>
                <li><a href="admin">Админ панель</a></li>
              <% end %>
              <!--<li><a href="#">Личный кабинет</a></li>-->
              <!--<li><a href="#">Настройки</a></li>-->
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Выйти', logout_path, method: 'delete' %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Войти', 'login' %></li>
          <li><%= link_to 'Зарегистрироваться', 'signup' %></li>
        </ul>
      <% end %>
      </div>
    </div>
  </nav>
</header>
<%= yield %>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4 sitemap">
        <h3>Карта сайта</h3>
        <div class="row">
          <div class="col-md-6">
            <%= link_to 'Главная', '/' %>
            <%= link_to 'Новости', '/posts' %>
            <%= link_to 'Тендеры', '/tenders' %>
          </div>
          <div class="col-md-6">
            <a href="/partners/">О нас</a>
            <a href="/customers/">Поддержка</a>
            <a href="/contact/">Контакты</a>
          </div>
        </div>
      </div>
      <div class="col-md-4 social">
        <h3>Социальные сети</h3>
        <a href="//twitter.com/" class="social-icon twitter"></a>
        <a href="//facebook.com/" class="social-icon facebook"></a>
        <a href="//plus.google.com/" class="social-icon vk"></a><br>
        <a href="//github.com/" class="social-icon github"></a>
        <a href="//bitbucket.org/" class="social-icon bitbucket"></a>
        <a href="//plus.google.com/" class="social-icon google-plus"></a>
      </div>
      <div class="col-md-4 footer-logo">
        <%= link_to image_tag('logo_on_transparent_372x75.png', size: '350x50'), '/' %>
        <p>
          Copyright © 2016 Tender.
        </p>
      </div>
    </div>
  </div>
</footer>
</body>
</html>

app/views/pages/admin_areas.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href="admin_tenders">Tenders</a></li>
        <!--<li><a href="#">Posts</a></li>-->
        <!--<li><a href="#">Users</a></li>-->
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="admin_categories">Categories</a></li>
        <li class="active"><a href="admin_areas">Areas</a></li>
        <!--<li><a href="">Tags</a></li>-->
      </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <h1 class="page-header">Admin panel</h1>
      <h2 class="sub-header">Categories</h2>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>#</th>
            <th>name_en</th>
            <th>name_ru</th>
            <th>created_at</th>
            <th>updated_at</th>
            <th>action</th>
          </tr>
          </thead>
          <tbody>
          <% @areas.each do |t| %>
              <tr>
                <td><%= t.id %></td>
                <td><%= t.name_en %></td>
                <td><%= t.name_ru %></td>
                <td width="100px"><%= t.created_at.strftime("%d.%m.%Y") %></td>
                <td width="100px"><%= t.updated_at.strftime("%d.%m.%Y") %></td>
                <td><a type="button" class="btn btn-default" href="areas/<%= t.id %>/edit">EDIT</a></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/pages/admin_categories.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href="admin_tenders">Tenders</a></li>
        <!--<li><a href="#">Posts</a></li>-->
        <!--<li><a href="#">Users</a></li>-->
      </ul>
      <ul class="nav nav-sidebar">
        <li class="active"><a href="admin_categories">Categories</a></li>
        <li><a href="admin_areas">Areas</a></li>
        <!--<li><a href="">Tags</a></li>-->
      </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <h1 class="page-header">Admin panel</h1>
      <h2 class="sub-header">Categories</h2>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>#</th>
            <th>name_en</th>
            <th>name_ru</th>
            <th>created_at</th>
            <th>updated_at</th>
            <th>action</th>
          </tr>
          </thead>
          <tbody>
          <% @categories.each do |t| %>
              <tr>
                <td><%= t.id %></td>
                <td><%= t.name_en %></td>
                <td><%= t.name_ru %></td>
                <td width="100px"><%= t.created_at.strftime("%d.%m.%Y") %></td>
                <td width="100px"><%= t.updated_at.strftime("%d.%m.%Y") %></td>
                <td><a type="button" class="btn btn-default" href="categories/<%= t.id %>/edit">EDIT</a></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/pages/admin_tenders.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="admin_tenders">Tenders</a></li>
        <!--<li><a href="#">Posts</a></li>-->
        <!--<li><a href="#">Users</a></li>-->
      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="admin_categories">Categories</a></li>
        <li><a href="admin_areas">Areas</a></li>
        <!--<li><a href="">Tags</a></li>-->
      </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <h1 class="page-header">Admin panel</h1>
      <form name="search" action="/admin_tenders" method="get" class="form-inline form-search pull-right">
        <div class="input-group">
          <label class="sr-only" for="searchInput">Search</label>
          <input class="form-control" id="searchInput" type="text" name="tenders_like" placeholder="Search" value="<%= params[:tenders_like] %>">
          <div class="input-group-btn">
            <button type="submit" class="btn btn-primary">Искать</button>
          </div>
        </div>
      </form>
      <h2 class="sub-header">Tenders</h2>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>#</th>
            <th>Purchase subject</th>
            <th>Category</th>
            <th>Area and address</th>
            <th>Date of publication</th>
            <th>Deadline date</th>
          </tr>
          </thead>
          <tbody>
          <% @tenders.each do |t| %>
              <tr>
                <td><%= t.id %></td>
                <td><%= link_to t.title, tender_path(t) %></td>
                <td width="90px"><%= link_to t.category.name_en, tenders_path(category: t.category) %></td>
                <td width="250px">
                  <%= link_to t.area.name_en, tenders_path(area: t.area) %><br>
                  <%= t.address %>
                </td>
                <td width="100px"><%= t.deadline.strftime("%d.%m.%Y") %></td>
                <td width="100px"><%= t.created_at.strftime("%d.%m.%Y") %></td>
                <td>
                  <div class="dropdown">
                    <button type="button" class="btn btn-default" data-toggle="dropdown" href="#">ACTIONS</button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                      <li><%= link_to 'MODER', 'tenders/update_status/' + t.id.to_s , method: 'get' %></li>
                      <li><%= link_to 'DELETE', tender_path(t), method: 'delete' %></li>
                    </ul>
                  </div>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Тендер онлайн</h1>
    <p>лучший выбор для тех, кто хочет преуспеть в бизенесе</p>
    <% unless current_user %>
    <p><%= link_to 'Присоедениться', 'signup',  class: 'btn btn-primary btn-lg' %></p>
    <p><%= link_to 'или войти', 'login' %></p>
    <% else %>
        <p><%= link_to 'Просмотреть текущие тендеры', 'tenders',  class: 'btn btn-primary btn-lg' %></p>
    <% end %>
    <%= image_tag 'Biznes-sdelka.jpg' %>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="b-home-list row">
    <div class="col-md-4">
      <span class="glyphicon glyphicon-usd"></span>
      <h3>Ассоциация успешных</h3>
      <p>Великое количество пользователей со своими товарами и услугами.</p>
    </div>
    <div class="col-md-4">
      <span class="glyphicon glyphicon-user"></span>
      <h3>Без посредников</h3>
      <p>Ведите дела напрямую с заказчиком или исполнителем.</p>
    </div>
    <div class="col-md-4">
      <span class="glyphicon glyphicon-phone"></span>
      <h3>Всегда под рукой</h3>
      <p>Возможность пользоваться ресурсом с мобильных устройств.</p>
    </div>
  </div>
  <div class="b-home-body row">
    <div class="col-md-3 col-md-offset-1">
      <%= image_tag '//jumgal.kg/wp-content/uploads/2016/04/ImageGen.jpg' %>
    </div>
    <div class="col-md-7 col-md-offset-1">
      <p>
        Те́ндер (англ. tender — предложение) — конкурентная форма отбора предложений на поставку товаров, оказание услуг или выполнение работ по заранее объявленным в документации условиям, в оговоренные сроки на принципах состязательности, справедливости и эффективности. Контракт заключается с победителем тендера — участником, подавшим предложение, соответствующее требованиям документации, в котором предложены наилучшие условия.
      </p>
      <p>
        В современных условиях торги являются распространенным способом размещения заказов на поставки машин и оборудования, выполнение научных, проектных и изыскательских работ, сооружение промышленных и социальных объектов. При этом законодательства большинства стран позволяют организациям с участием государственного капитала размещать заказы на приобретение товаров и услуг только через торги. Таким образом, торги это конкурсная форма поиска деловых партнеров, при которой фирма инициатор (заказчик) или несколько таких фирм путем публикации информации о предстоящих торгах привлекают к установленному сроку предложения (оферты) от заинтересованных фирм (оферентов). Заказчики создают тендерные комитеты, в состав которых входят технические и коммерческие эксперты, представители администрации. Тендерные комитеты осуществляют всю организационную работу по проведению торгов. Они публикуют объявления о торгах, распространяют между их участниками так называемую проформу тендерного предложения, представляющий собой типичную форму тендерного предложения. Тендерное предложение (оферта) письменное предложение, представленное оферентом (участником торгов) в адрес тендерного комитета с описанием предлагаемых товаров и услуг. Оферта может содержать и альтернативные предложения, содержащие несколько отличные условия от основного предложения, что повышает конкурентоспособность оферента на торгах.
      </p>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% @title = 'Editing'
   @heading = 'Editing' %>
<div class="container">
    <%= form_for(@post) do |f| %>
        <div class="form-group">
          <%= f.label :title_en %>
          <%= f.text_field :title_en, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :title_ru, 'Заголовок' %>
          <%= f.text_field :title_ru, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :text_en %>
          <%= f.text_area :text_en, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :text_ru %>
          <%= f.text_area :text_ru, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= image_tag(@post.preview, size: '170x130') %>
          <%= file_field(:post, :preview, accept: 'image/png,image/gif,image/jpeg') %>
        </div>
        <div class="action">
          <%= f.submit "Update", class: 'btn btn-default' %>
        </div>
    <% end %>
</div>

app/views/posts/index.html.erb
<% @title = 'News' %>

<div class="news container">
  <% @posts.each do |p| %>
      <ul class="post">
        <li><h3><%= p.title_en %></h3></li>
        <li><%= image_tag(p.preview, size: '360x240') %></li>
        <li><p><%= p.text_en %></p></li>
        <li><a href="#">Подробнее</a></li>
      </ul>
      <hr>
  <% end %>
</div>

app/views/posts/new.html.erb
<% @title = 'Creating a new post'
   @heading = 'New post' %>
<div class="container">
  <%= form_for(@post) do |f| %>
      <div class="form-group">
        <%= f.label :title_en %>
        <%= f.text_field :title_en, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :title_ru, 'Заголовок' %>
        <%= f.text_field :title_ru, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :text_en %>
        <%= f.text_area :text_en, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :text_ru %>
        <%= f.text_area :text_ru, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= file_field(:post, :preview, accept: 'image/png,image/gif,image/jpeg') %>
      </div>
      <div class="action">
        <%= f.submit "Update", class: 'btn btn-default' %>
      </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<% @title = @post.title_en
   @heading = @post.title_en %>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h3><%= @post.title_en %></h3>
      <p><%= @post.text_en %></p>
      <!--<p>by <%= link_to @post.user.email, user_path(@post.user) %></p>-->
      <p>by <%= link_to @post.user.email, '#' %></p>
      <p><%= @post.created_at %></p>
    </div>
    <div class="col-md-3 ">
      <%= image_tag @post.preview, size: '360x240', style: 'margin-top:20px' %>
    </div>
  </div>
</div>

app/views/tenders/index.html.erb
<% @title = 'Тендеры' %>

<div class="container">
  <section class="col-md-9">
    <a type="button" href="tenders/new" class="btn btn-default">Создать новый тендер</a>
    <form name="search" action="/tenders" method="get" class="form-inline form-search pull-right">
      <div class="input-group">
        <label class="sr-only" for="searchInput">Search</label>
        <input class="form-control" id="searchInput" type="text" name="tenders_like" placeholder="Поиск..." value="<%= params[:tenders_like] %>">
        <div class="input-group-btn">
          <button type="submit" class="btn btn-primary">Искать</button>
        </div>
      </div>
    </form>
    <!--<button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#cat">
          simple collapsible
        </button>

        <div id="cat" class="collapse">
          <div class="row">
            <div>
              <ul>
                <%= @categories.each do |c| %>
                  <li class="cat"><%= link_to c.name_ru, tenders_path(category: c) %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>-->
    <% if @tenders.exists? %>
        <table class="table table-hover">
          <thead>
          <tr>
            <!--<td>Category</td>
            <td>Purchase subject</td>
            <td>Area and address</td>
            <td>Date of publication</td>
            <td>Deadline date</td>-->
            <th>Категория</th>
            <th>Предмет закупки</th>
            <th>Адрес, место поставки</th>
            <th>Дата публикации</th>
            <th>Deadline</th>
          </tr>
          </thead>
          <tbody>
          <% @tenders.each do |t| %>
              <tr>
                <td width="90px"><%= link_to t.category.name_ru, tenders_path(category: t.category) %></td>
                <td><%= link_to t.title, tender_path(t) %></td>
                <td width="250px">
                  <%= link_to t.area.name_en, tenders_path(area: t.area) %><br>
                  <%= t.address %>
                </td>
                <td width="100px"><%= t.deadline.strftime("%d.%m.%Y") %></td>
                <td width="100px"><%= t.created_at.strftime("%d.%m.%Y") %></td>
              </tr>
          <% end %>
    <% else %>
        <h3>По вашему запросу ничего не найдено</h3>
    <% end %>
    </tbody>
    </table>
  </section>
  <aside class="col-md-3">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading"><%= link_to 'Новости', '/posts' %></div>
      <!-- List group -->
      <ul class="list-group">
        <% @posts.each do |p| %>
            <li class="list-group-item">
              <ul class="post">
                <%= link_to post_path(p) do %>
                    <li><h4><%= p.title_en %></h4></li>
                    <li><%= image_tag(p.preview, size: '170x130') %></li>
                <% end %>
              </ul>
            </li>
        <% end %>
      </ul>
    </div>
  </aside>
</div>


<div class="container">
  <div class="row"></div>
</div>

app/views/tenders/new.html.erb
<% @title = 'Новый тендер'
   @heading = 'Новый тендер' %>
<div class="container">
  <div class="form">
    <%= form_for(@tender) do |f| %>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :title, 'Заголовок' %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :content, 'Описание' %>
            <%= f.text_area :content, class: 'form-control', rows: "15" %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :amount, 'Сумма закупки' %>
            <%= f.number_field :amount, class: 'form-control' %>
            <%= f.select(:currency, {}, {}, {class: 'form-control'}) do %>
                <%= content_tag(:option, 'UAH', value: 'UAH') %>
                <%= content_tag(:option, 'USD', value: 'USD') %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :address, 'Адрес' %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :area, 'Регион' %>
            <%= f.select(:area, {}, {}, {class: 'form-control'}) do %>
                <% @areas.each do |a| -%>
                    <%= content_tag(:option, a.name_ru, value: a.id) %>
                <% end %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :category, 'Категория' %>
            <%= f.select(:category, {}, {}, {class: 'form-control'}) do %>
                <% @categories.each do |a| -%>
                    <%= content_tag(:option, a.name_ru, value: a.id) %>
                <% end %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :deadline, 'Дата подачи предложений' %>
            <%= f.date_select :deadline, :start_year => 2016, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-12">
          <div class="action">
            <%= f.submit 'Создать', class: 'btn btn-default' %>
          </div>
        </div>
    <% end %>
  </div>
</div>